name: Build all
on:
  push:
    branches:
      - master
jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up QEMU     
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Publish Unified Backend
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./docker/desktop/backend.Dockerfile
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: |
            ghcr.io/sourcescapeio/backend:latest
            ghcr.io/sourcescapeio/backend:1.0

  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up QEMU     
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Publish Primadonna
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./docker/desktop/primadonna.Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/sourcescapeio/primadonna:latest
            ghcr.io/sourcescapeio/primadonna:1.0

      - name: Build and Publish Proxy
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./docker/desktop/proxy.Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/sourcescapeio/proxy:latest
            ghcr.io/sourcescapeio/proxy:1.0

      - name: Build and Publish Frontend
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./docker/desktop/frontend.Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/sourcescapeio/frontend:latest
            ghcr.io/sourcescapeio/frontend:1.0
