name: Build all
on:
  push:
    branches:
      - drj/actions
jobs:
  build-prima:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout repository

      - uses: pmorelli92/github-container-registry-build-push@2.0.0
        name: Build and Publish latest service image
        with:
          github-push-secret: ${{secrets.GITHUB_TOKEN}}
          docker-image-name: primadonna
          docker-image-tag: latest # optional
          dockerfile-path: ./docker/desktop/primadonna.Docker # optional
          build-context: ./ # optional
