name: Build all
on:
  push:
    branches:
      - drj/actions
jobs:
  build-all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout repository

      - uses: pmorelli92/github-container-registry-build-push@2.0.0
        name: Build and Publish Primadonna
        with:
          github-push-secret: ${{secrets.GITHUB_TOKEN}}
          docker-image-name: primadonna
          docker-image-tag: 1.0.0 # optional
          dockerfile-path: ./docker/desktop/primadonna.Dockerfile # optional
          build-context: ./ # optional

      - uses: pmorelli92/github-container-registry-build-push@2.0.0
        name: Build and Publish API
        with:
          github-push-secret: ${{secrets.GITHUB_TOKEN}}
          docker-image-name: api
          docker-image-tag: 1.0.0 # optional
          dockerfile-path: ./docker/desktop/api.Dockerfile # optional
          build-context: ./ # optional

      - uses: pmorelli92/github-container-registry-build-push@2.0.0
        name: Build and Publish Indexer
        with:
          github-push-secret: ${{secrets.GITHUB_TOKEN}}
          docker-image-name: indexer
          docker-image-tag: 1.0.0 # optional
          dockerfile-path: ./docker/desktop/indexer.Dockerfile # optional
          build-context: ./ # optional

      - uses: pmorelli92/github-container-registry-build-push@2.0.0
        name: Build and Publish Proxy
        with:
          github-push-secret: ${{secrets.GITHUB_TOKEN}}
          docker-image-name: proxy
          docker-image-tag: 1.0.0 # optional
          dockerfile-path: ./docker/desktop/proxy.Dockerfile # optional
          build-context: ./ # optional

      - uses: pmorelli92/github-container-registry-build-push@2.0.0
        name: Build and Publish Initializer
        with:
          github-push-secret: ${{secrets.GITHUB_TOKEN}}
          docker-image-name: initializer
          docker-image-tag: 1.0.0 # optional
          dockerfile-path: ./docker/desktop/initializer.Dockerfile # optional
          build-context: ./ # optional

      - uses: pmorelli92/github-container-registry-build-push@2.0.0
        name: Build and Publish Frontend
        with:
          github-push-secret: ${{secrets.GITHUB_TOKEN}}
          docker-image-name: frontend
          docker-image-tag: 1.0.0 # optional
          dockerfile-path: ./docker/desktop/frontend.Dockerfile # optional
          build-context: ./ # optional
